# Generated by Django 2.0.5 on 2018-05-10 09:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True)),
                ('date', models.DateTimeField()),
                ('post_init', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Departament',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('init', models.CharField(max_length=32)),
                ('admin', models.CharField(max_length=32)),
                ('name', models.CharField(blank=True, max_length=255, unique=True)),
                ('date_create', models.DateTimeField(null=True)),
                ('image', models.ImageField(blank=True, upload_to='group/', verbose_name='')),
                ('public_key', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='LastMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('companion_1', models.CharField(blank=True, max_length=32)),
                ('companion_2', models.CharField(blank=True, max_length=32)),
                ('text', models.TextField()),
                ('id_msg', models.IntegerField()),
                ('type_msg', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Likes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_init', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(blank=True, max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(blank=True, max_length=32)),
                ('user', models.CharField(blank=True, max_length=32)),
                ('companion', models.CharField(blank=True, max_length=32)),
                ('text', models.TextField()),
                ('img', models.CharField(max_length=255, null=True)),
                ('type_msg', models.CharField(blank=True, choices=[('1', 'text'), ('2', 'file'), ('3', 'link')], default=False, max_length=255)),
                ('date', models.DateTimeField(null=True)),
                ('delivered', models.BooleanField(default=False)),
                ('reading', models.BooleanField(default=False)),
                ('crypting', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('text', models.TextField()),
                ('date', models.DateTimeField()),
                ('users_from', models.TextField()),
                ('comment', models.ManyToManyField(blank=True, to='users.Comment')),
            ],
        ),
        migrations.CreateModel(
            name='Storage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_file', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('path', models.CharField(max_length=255)),
                ('hash_name', models.CharField(max_length=255)),
                ('url', models.CharField(max_length=255)),
                ('date', models.DateTimeField(null=True)),
                ('cache', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('init', models.CharField(blank=True, max_length=32)),
                ('image', models.ImageField(blank=True, upload_to='user/', verbose_name='')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('password', models.CharField(max_length=150)),
                ('hash_password', models.CharField(blank=True, max_length=150)),
                ('email', models.CharField(max_length=255)),
                ('phone', models.CharField(blank=True, max_length=255)),
                ('position', models.CharField(max_length=255)),
                ('subordinate', models.TextField(blank=True)),
                ('about', models.TextField(blank=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('status', models.BooleanField(default=False)),
                ('public_key_user', models.CharField(blank=True, max_length=255)),
                ('dep', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.Departament')),
                ('group', models.ManyToManyField(blank=True, to='users.Group')),
            ],
        ),
        migrations.CreateModel(
            name='Views',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_init', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.User')),
            ],
        ),
        migrations.AddField(
            model_name='storage',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.User'),
        ),
        migrations.AddField(
            model_name='post',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.User'),
        ),
        migrations.AddField(
            model_name='post',
            name='likes',
            field=models.ManyToManyField(blank=True, to='users.Likes'),
        ),
        migrations.AddField(
            model_name='post',
            name='views',
            field=models.ManyToManyField(blank=True, to='users.Views'),
        ),
        migrations.AddField(
            model_name='message',
            name='reading_group',
            field=models.ManyToManyField(blank=True, to='users.User'),
        ),
        migrations.AddField(
            model_name='membership',
            name='users',
            field=models.ManyToManyField(blank=True, to='users.User'),
        ),
        migrations.AddField(
            model_name='likes',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.User'),
        ),
        migrations.AddField(
            model_name='comment',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.User'),
        ),
    ]
