# Generated by Django 2.0.1 on 2018-02-05 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('companion', models.IntegerField(null=True)),
                ('text', models.TextField()),
                ('type_msg', models.CharField(blank=True, choices=[('1', 'text'), ('2', 'file'), ('3', 'link')], default=False, max_length=255)),
                ('date', models.DateTimeField(null=True)),
                ('delivered', models.BooleanField(default=False)),
                ('reading', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Storage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_file', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('path', models.CharField(max_length=255)),
                ('hash_name', models.CharField(max_length=255)),
                ('url', models.CharField(max_length=255)),
                ('date', models.DateTimeField(null=True)),
                ('data', models.BinaryField(null=True)),
                ('cache', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='user/', verbose_name='')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('password', models.CharField(max_length=150)),
                ('hash_password', models.CharField(blank=True, max_length=150)),
                ('email', models.CharField(max_length=255)),
                ('phone', models.CharField(blank=True, max_length=255)),
                ('position', models.CharField(max_length=255)),
                ('subordinate', models.TextField(blank=True)),
                ('about', models.TextField(blank=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('status', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='storage',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.User'),
        ),
        migrations.AddField(
            model_name='message',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.User'),
        ),
    ]
