# Generated by Django 2.0.1 on 2018-02-06 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='publick_key',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
