# Generated by Django 2.0.1 on 2018-01-25 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20180125_0414'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='companion',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='reading',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='message',
            name='type_msg',
            field=models.CharField(choices=[('1', 'text'), ('2', 'img'), ('3', 'file'), ('4', 'link')], default=False, max_length=255),
        ),
        migrations.AlterField(
            model_name='message',
            name='text',
            field=models.TextField(),
        ),
    ]
