# Generated by Django 2.0.1 on 2018-02-06 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_publick_key'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='publick_key',
            new_name='public_key',
        ),
    ]
