# Generated by Django 2.0.1 on 2018-02-06 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20180206_1504'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='public_key',
            new_name='public_key_user',
        ),
    ]
