# Generated by Django 2.0.1 on 2018-01-27 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20180126_0509'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='message',
            name='type_msg',
            field=models.CharField(blank=True, choices=[('1', 'text'), ('2', 'img'), ('3', 'file'), ('4', 'link')], default=False, max_length=255),
        ),
    ]
