# Generated by Django 2.0.1 on 2018-02-07 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20180206_1531'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storage',
            name='data',
        ),
    ]
