# Generated by Django 2.0.1 on 2018-02-13 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_storage_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='LastMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('companion_1', models.IntegerField()),
                ('companion_2', models.IntegerField()),
                ('text', models.TextField()),
            ],
        ),
    ]
