# Generated by Django 2.0.1 on 2018-02-13 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_lastmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='lastmessage',
            name='type_msg',
            field=models.CharField(default='text', max_length=10),
            preserve_default=False,
        ),
    ]
