# Generated by Django 2.0.1 on 2018-02-13 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_lastmessage_type_msg'),
    ]

    operations = [
        migrations.AddField(
            model_name='lastmessage',
            name='id_msg',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
