# Generated by Django 2.0.1 on 2018-02-13 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_lastmessage_id_msg'),
    ]

    operations = [
        migrations.AddField(
            model_name='lastmessage',
            name='name',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
