# Generated by Django 2.0.1 on 2018-02-13 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_lastmessage_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lastmessage',
            name='name',
        ),
    ]
