# Generated by Django 2.0.1 on 2018-02-14 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_group_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group',
            old_name='users',
            new_name='user',
        ),
    ]
