# Generated by Django 2.0.1 on 2018-02-14 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_auto_20180214_1038'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group',
            old_name='user',
            new_name='users',
        ),
    ]
