# Generated by Django 2.0.1 on 2018-02-14 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_auto_20180214_1058'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='img',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
