# Generated by Django 2.0.1 on 2018-02-16 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_membership'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='init',
            field=models.CharField(default=1, max_length=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='init',
            field=models.CharField(default=1, max_length=32),
            preserve_default=False,
        ),
    ]
