# Generated by Django 2.0.1 on 2018-02-16 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_auto_20180216_0819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='companion',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='message',
            name='user',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='user',
            name='init',
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
