# Generated by Django 2.0.1 on 2018-02-16 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_auto_20180216_0901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lastmessage',
            name='companion_1',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='lastmessage',
            name='companion_2',
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
