# Generated by Django 2.0.1 on 2018-02-16 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_auto_20180216_0931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='group',
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
