# Generated by Django 2.0.1 on 2018-02-16 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_auto_20180216_1117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='group',
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
