# Generated by Django 2.0.1 on 2018-02-20 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0026_group_public_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='image',
            field=models.ImageField(blank=True, upload_to='group/', verbose_name=''),
        ),
    ]
