# Generated by Django 2.0.1 on 2018-03-15 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0027_group_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='name',
            field=models.CharField(blank=True, max_length=255, unique=True),
        ),
    ]
