# Generated by Django 2.0.1 on 2018-04-17 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0034_auto_20180417_1210'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='likes',
            name='post_likes',
        ),
        migrations.RemoveField(
            model_name='views',
            name='post_views',
        ),
    ]
