# Generated by Django 2.0.1 on 2018-04-17 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0035_auto_20180417_1216'),
    ]

    operations = [
        migrations.AddField(
            model_name='likes',
            name='post_likes',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='views',
            name='post_views',
            field=models.CharField(default=213, max_length=255),
            preserve_default=False,
        ),
    ]
