# Generated by Django 2.0.1 on 2018-04-17 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0036_auto_20180417_1218'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='crypting',
            field=models.BooleanField(default=False),
        ),
    ]
