# Generated by Django 2.0.1 on 2018-04-19 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0037_message_crypting'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='likes',
            name='post_likes',
        ),
        migrations.RemoveField(
            model_name='views',
            name='post_views',
        ),
        migrations.AddField(
            model_name='comment',
            name='post_init',
            field=models.IntegerField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='likes',
            name='post_init',
            field=models.IntegerField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='views',
            name='post_init',
            field=models.IntegerField(default='1', max_length=255),
            preserve_default=False,
        ),
    ]
