# Generated by Django 2.0.4 on 2018-04-30 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0038_auto_20180419_1044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='post_init',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='likes',
            name='post_init',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='views',
            name='post_init',
            field=models.IntegerField(),
        ),
    ]
