# Generated by Django 2.0.4 on 2018-04-30 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0039_auto_20180430_1847'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='users_from',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
