# Generated by Django 2.0.4 on 2018-04-30 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0040_post_users_from'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='likes',
            name='type_like',
        ),
    ]
